Question no.1 :- Given three integer arrays arr1, arr2 and arr3 sorted in strictly increasing order, return a sorted array of only the integers that appeared in all three arrays.

Example 1:

Input: arr1 = [1,2,3,4,5], arr2 = [1,2,5,7,9], arr3 = [1,3,4,5,8]

Output: [1,5]

Explanation: Only 1 and 5 appeared in the three arrays.

Answer no.1

In [ ]:
class Three_arr_common:
    def find_common(self, arr1, arr2, arr3):
        
        result = []
        i, j, k = 0, 0, 0

        while i != len(arr1) and j != len(arr2) and k != len(arr3):
            if arr1[i] == arr2[j] == arr3[k]:
                result.append(arr1[i])
                i += 1
                j += 1
                k += 1
            else:
                curr = max(arr1[i], arr2[j], arr3[k])
                while i != len(arr1) and arr1[i] < curr:
                    i += 1
                while j != len(arr2) and arr2[j] < curr:
                    j += 1
                while k != len(arr3) and arr3[k] < curr:
                    k += 1
        return result

obj = Three_arr_common()
arr1 = [1,2,4,6,9]
arr2 = [4,5,6,7,9]
arr3 = [3,4,6,7,9]
print(obj.find_common(arr1,arr2,arr3))

[4, 6, 9]

Question no.2 :- Given two 0-indexed integer arrays nums1 and nums2, return a list answer of size 2 where:

answer[0] is a list of all distinct integers in nums1 which are not present in nums2.
answer[1] is a list of all distinct integers in nums2 which are not present in nums1.
Note that the integers in the lists may be returned in any order.

Example 1:

Input: nums1 = [1,2,3], nums2 = [2,4,6]

Output: [[1,3],[4,6]]

Explanation:

For nums1, nums1[1] = 2 is present at index 0 of nums2, whereas nums1[0] = 1 and nums1[2] = 3 are not present in nums2. Therefore, answer[0] = [1,3].

For nums2, nums2[0] = 2 is present at index 1 of nums1, whereas nums2[1] = 4 and nums2[2] = 6 are not present in nums2. Therefore, answer[1] = [4,6].

Answer no.2

In [1]:
class Distinct_nums:
    def find_uncommon(self,nums1,nums2):
        Set1=set(nums1)
        Set2=set(nums2)
        res1=list(set(i for i in nums1 if i not in Set2))
        res2=list(set(i for i in nums2 if i not in Set1))
        return [res1,res2]

obj1 = Distinct_nums() 
nums1 = [1,2,3]
nums2 = [2,4,6]
print(obj1.find_uncommon(nums1,nums2))

[[1, 3], [4, 6]]

Question no.3 :- Given a 2D integer array matrix, return *the **transpose** of* matrix.
The transpose of a matrix is the matrix flipped over its main diagonal, switching the matrix's row and column indices.

Example 1:

Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]

Output: [[1,4,7],[2,5,8],[3,6,9]]

Answer no.3

In [ ]:
import numpy as np
class Array_Transpose:
    def to_transpose(self,arr): 
        
        array_T= arr.transpose()
        return array_T

obj2 = Array_Transpose()
arr = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print(obj2.to_transpose(arr))

[[1 4 7]
 [2 5 8]
 [3 6 9]]

Question no.4 :- Given an integer array nums of 2n integers, group these integers into n pairs (a1, b1), (a2, b2), ..., (an, bn) such that the sum of min(ai, bi) for all i is **maximized**. Return *the maximized sum*.

Example 1:

Input: nums = [1,4,3,2]

Output: 4

Explanation: All possible pairings (ignoring the ordering of elements) are:

(1, 4), (2, 3) -> min(1, 4) + min(2, 3) = 1 + 2 = 3

(1, 3), (2, 4) -> min(1, 3) + min(2, 4) = 1 + 2 = 3

(1, 2), (3, 4) -> min(1, 2) + min(3, 4) = 1 + 3 = 4

So the maximum possible sum is 4.

Answer no.4

In [ ]:
class Max_of_min:
    def max_min_sum(self,nums):
        
        nums.sort()

        return sum([i for i in nums[::2]])

obj3 = Max_of_min() 
nums = [1,4,3,2]
print(obj3.max_min_sum(nums))

4

Question no.5 :- You have n coins and you want to build a staircase with these coins. The staircase consists of k rows where the ith row has exactly i coins. The last row of the staircase **may be** incomplete.
Given the integer n, return the number of complete rows of the staircase you will build.

Example 1:

Input: n = 5

Output: 2

Explanation: Because the 3rd row is incomplete, we return 2.

Answer no.5

In [ ]:
class Staircase:
    def arrange_coins(self,n):
        coin_counter = 0
        rows = 0
        
        if n == 1:
            return 1

        while coin_counter+(rows+1) <= n:
            rows += 1
            coin_counter = coin_counter + rows
        
        return rows

obj4 = Staircase() 
n = 10
print(obj4.arrange_coins(n))

4

Question no.6 :- Given an integer array nums sorted in **non-decreasing** order, return *an array of **the squares of each number** sorted in non-decreasing order*.

Example 1:

Input: nums = [-4,-1,0,3,10]

Output: [0,1,9,16,100]

Explanation: After squaring, the array becomes [16,1,0,9,100]. After sorting, it becomes [0,1,9,16,100]

Answer no.6

In [ ]:
class Squares_arr:
    def get_squares(self,list):
        sq_list = []
        
        for ele in list:
            sq_list.append(ele**2)
             
        return sorted(sq_list) 

obj5 = Squares_arr() 
list = [-4,-1,0,3,10]
print(obj5.get_squares(list))

[0, 1, 9, 16, 100]

Question no.7 :- You are given an m x n matrix M initialized with all 0's and an array of operations ops, where ops[i] = [ai, bi] means M[x][y] should be incremented by one for all 0 <= x < ai and 0 <= y < bi.
Count and return the number of maximum integers in the matrix after performing all the operations

Example 1:

Input: m = 3, n = 3, ops = [[2,2],[3,3]]

Output: 4

Explanation: The maximum integer in M is 2, and there are four of it in M. So return 4.

Answer no.7

In [ ]:
class Matrix_ele:
    def count_ele(self,m,n,ops):
        
        for op in ops:
            m = min(m, op[0])
            n = min(n, op[1])
        return m*n

obj6 = Matrix_ele()
m = 3
n = 3
ops = [[2,2],[3,3]]
print(obj6.count_ele(m,n,ops))

4

Question no.8 :-
Given the array nums consisting of 2n elements in the form [x1,x2,...,xn,y1,y2,...,yn].

Return the array in the form [x1,y1,x2,y2,...,xn,yn].

Example 1:

Input: nums = [2,5,1,3,4,7], n = 3

Output: [2,3,5,4,1,7]

Explanation: Since x1=2, x2=5, x3=1, y1=3, y2=4, y3=7 then the answer is [2,3,5,4,1,7].

Answer no.8

In [ ]:
class Shift_nums:
    def get_shift(self,nums,n):
        i=0
        j=n
        res=[]
        
        while(i<n):
            res.append(nums[i])
            res.append(nums[j])
            i+=1
            j+=1
        return res

obj7 = Shift_nums() 
nums = [1,3,5,2,4,6]
n = 3 
print(obj7.get_shift(nums,n))

[1, 2, 3, 4, 5, 6]